apiVersion: v1
kind: Pod
metadata:
  name: python-cd
  labels:
    app: app-cd
spec:
  serviceAccountName: new-ns
  containers:
  - image: python
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: cd
  restartPolicy: Always
